"""Model package.

Importing this module imports every mapped class, which is what SQLAlchemy needs
before `Base.metadata.create_all` or any cross-module relationship can resolve.
Domain modules import from here rather than reaching into a sibling's file.
"""

from app.models.base import (
    AccountStatus,
    AgeingBucket,
    AllocationRule,
    AssetStatus,
    AttemptClass,
    Base,
    CallStatus,
    CampaignStatus,
    Channel,
    DndStatus,
    EscalationLevel,
    EventSource,
    InvoiceStatus,
    MessageStatus,
    TimestampMixin,
    account_status_t,
    ageing_bucket_t,
    allocation_rule_t,
    asset_status_t,
    call_status_t,
    campaign_status_t,
    channel_t,
    dnd_status_t,
    escalation_level_t,
    event_source_t,
    invoice_status_t,
    message_status_t,
)
from app.models.comms import (
    AudioAsset,
    ChannelOptOut,
    Message,
    MessageEvent,
    MessageTemplate,
    TemplateVersion,
)
from app.models.ingestion import (
    ErpConnection,
    ImportBatch,
    ImportRow,
    ProviderFetch,
    SyncRun,
)
from app.models.company import (
    CompanyProfile,
    EntityCandidate,
    GstRecord,
    McaRecord,
    VerificationReport,
)
from app.models.intelligence import CreditAssessment, PaymentBehaviour, Promise, RiskScore
from app.models.legal import (
    CaseParty,
    CourtCase,
    LegalHistory,
    LegalLink,
    LegalMatter,
    LegalNotice,
    PrelegalAssessment,
)
from app.models.registry import (
    ListingAudit,
    ListingDispute,
    ListingEvidence,
    RegistryListing,
    TraceAudit,
    TraceRequest,
    TraceResult,
)
from app.models.identity import ApiKey, AuditLog, CallerId, Company, RoleGrant, User
from app.models.recovery import BlackoutDate, Campaign, CampaignTarget, EscalationState
from app.models.trade import (
    Buyer,
    BuyerPhone,
    CreditAccount,
    CreditNote,
    Invoice,
    InvoiceLine,
    Payment,
    PaymentAllocation,
    Return,
    Seller,
    Statement,
)
from app.models.voice import Call, CallEvent

__all__ = [
    "AccountStatus",
    "AgeingBucket",
    "AllocationRule",
    "ApiKey",
    "AssetStatus",
    "AttemptClass",
    "AudioAsset",
    "AuditLog",
    "Base",
    "BlackoutDate",
    "Buyer",
    "BuyerPhone",
    "Call",
    "CallEvent",
    "CallStatus",
    "CallerId",
    "Campaign",
    "CampaignStatus",
    "CampaignTarget",
    "CaseParty",
    "Channel",
    "ChannelOptOut",
    "Company",
    "CompanyProfile",
    "CreditAssessment",
    "CourtCase",
    "CreditAccount",
    "CreditNote",
    "DndStatus",
    "EntityCandidate",
    "ErpConnection",
    "EscalationLevel",
    "EscalationState",
    "EventSource",
    "GstRecord",
    "ImportBatch",
    "ImportRow",
    "Invoice",
    "InvoiceLine",
    "InvoiceStatus",
    "LegalHistory",
    "LegalLink",
    "LegalMatter",
    "LegalNotice",
    "ListingAudit",
    "ListingDispute",
    "ListingEvidence",
    "McaRecord",
    "Message",
    "MessageEvent",
    "MessageStatus",
    "MessageTemplate",
    "Payment",
    "PaymentAllocation",
    "PaymentBehaviour",
    "PrelegalAssessment",
    "Promise",
    "ProviderFetch",
    "RegistryListing",
    "Return",
    "RiskScore",
    "RoleGrant",
    "Seller",
    "Statement",
    "SyncRun",
    "TemplateVersion",
    "TimestampMixin",
    "TraceAudit",
    "TraceRequest",
    "TraceResult",
    "User",
    "VerificationReport",
    "account_status_t",
    "ageing_bucket_t",
    "allocation_rule_t",
    "asset_status_t",
    "call_status_t",
    "campaign_status_t",
    "channel_t",
    "dnd_status_t",
    "escalation_level_t",
    "event_source_t",
    "invoice_status_t",
    "message_status_t",
]
