"""supabase external auth id on users

Revision ID: 08ca981ce365
Revises: 32f46f8f0936
Create Date: 2026-09-05 22:57:53.349195
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '08ca981ce365'
down_revision = '32f46f8f0936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('external_auth_id', sa.String(length=128), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_external_auth_id'), 'users', ['external_auth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_external_auth_id'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'external_auth_id')
    # ### end Alembic commands ###
