"""company intelligence, legal, registry, tracing

Revision ID: 32f46f8f0936
Revises: a3a080de9534
Create Date: 2026-09-05 21:15:43.028641
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '32f46f8f0936'
down_revision = 'a3a080de9534'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('court_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.String(length=64), nullable=False),
    sa.Column('court_name', sa.String(length=200), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('case_type', sa.String(length=64), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('next_hearing', sa.Date(), nullable=True),
    sa.Column('parties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'court_id', 'case_number')
    )
    op.create_index('ix_court_cases_filed', 'court_cases', ['company_id', 'filing_date'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=24), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_scores_subject', 'risk_scores', ['subject_type', 'subject_id', 'computed_at'], unique=False)
    op.create_table('case_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('raw_name', sa.String(length=400), nullable=False),
    sa.Column('normalised_name', sa.String(length=400), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['court_cases.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_parties_normalised_name'), 'case_parties', ['normalised_name'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=True),
    sa.Column('legal_name', sa.String(length=300), nullable=False),
    sa.Column('trade_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('additional_gstins', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('pan_hash', sa.String(length=64), nullable=True),
    sa.Column('pan_last4', sa.String(length=4), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('resolution_tier', sa.String(length=24), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_profiles_cin', 'company_profiles', ['company_id', 'cin'], unique=False)
    op.create_index('ix_company_profiles_gstin', 'company_profiles', ['company_id', 'gstin'], unique=False)
    op.create_table('entity_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.String(length=300), nullable=False),
    sa.Column('identifier_kind', sa.String(length=10), nullable=True),
    sa.Column('identifier_value', sa.String(length=21), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('tier', sa.String(length=24), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_behaviours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('invoices_settled', sa.Integer(), nullable=False),
    sa.Column('mean_days_to_pay', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('median_days_to_pay', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('days_to_pay_trend', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('part_payment_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('promise_kept_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('dispute_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('contact_response_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_behaviour_buyer', 'payment_behaviours', ['buyer_id', 'as_of'], unique=False)
    op.create_table('trace_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('lawful_basis', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gst_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=True),
    sa.Column('trade_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('filing_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'gstin', 'fetched_at')
    )
    op.create_table('legal_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_case_count', sa.BigInteger(), nullable=False),
    sa.Column('caveat', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['court_cases.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'profile_id')
    )
    op.create_table('mca_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('cin', sa.String(length=21), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=True),
    sa.Column('directors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('charges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('paid_up_capital_paise', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('lawful_basis', sa.String(length=80), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['trace_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trace_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=400), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['trace_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prelegal_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_cost_paise', sa.BigInteger(), nullable=True),
    sa.Column('recoverable_paise', sa.BigInteger(), nullable=True),
    sa.Column('limitation_expires_on', sa.Date(), nullable=True),
    sa.Column('limitation_urgent', sa.Boolean(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assessed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], ),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('promised_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('promised_on', sa.Date(), nullable=False),
    sa.Column('promised_by_date', sa.Date(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_notices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('template_version_id', sa.UUID(), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=False),
    sa.Column('figures_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatch_method', sa.String(length=32), nullable=True),
    sa.Column('tracking_reference', sa.String(length=100), nullable=True),
    sa.Column('delivery_proof', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_deadline', sa.Date(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['prelegal_assessments.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_matters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('notice_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('advocate_name', sa.String(length=200), nullable=True),
    sa.Column('advocate_contact', sa.String(length=200), nullable=True),
    sa.Column('court_name', sa.String(length=200), nullable=True),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('hearings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['court_cases.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['legal_notices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registry_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('listed_by_company_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('notice_id', sa.UUID(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('oldest_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delist_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['credit_accounts.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['listed_by_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['legal_notices.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_registry_status', 'registry_listings', ['status', 'published_at'], unique=False)
    op.create_table('listing_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['registry_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.String(length=200), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['registry_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['registry_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_template_current_version', 'message_templates', 'template_versions', ['current_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_template_current_version', 'message_templates', type_='foreignkey')
    op.drop_table('listing_evidence')
    op.drop_table('listing_disputes')
    op.drop_table('listing_audit')
    op.drop_index('ix_registry_status', table_name='registry_listings')
    op.drop_table('registry_listings')
    op.drop_table('legal_matters')
    op.drop_table('legal_notices')
    op.drop_table('promises')
    op.drop_table('prelegal_assessments')
    op.drop_table('verification_reports')
    op.drop_table('trace_results')
    op.drop_table('trace_audit')
    op.drop_table('mca_records')
    op.drop_table('legal_links')
    op.drop_table('legal_histories')
    op.drop_table('gst_records')
    op.drop_table('trace_requests')
    op.drop_index('ix_payment_behaviour_buyer', table_name='payment_behaviours')
    op.drop_table('payment_behaviours')
    op.drop_table('entity_candidates')
    op.drop_index('ix_company_profiles_gstin', table_name='company_profiles')
    op.drop_index('ix_company_profiles_cin', table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_case_parties_normalised_name'), table_name='case_parties')
    op.drop_table('case_parties')
    op.drop_index('ix_risk_scores_subject', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_court_cases_filed', table_name='court_cases')
    op.drop_table('court_cases')
    # ### end Alembic commands ###
