"""credit assessments

Revision ID: 965d9af3e0c7
Revises: 08ca981ce365
Create Date: 2026-09-06 03:24:14.829395
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '965d9af3e0c7'
down_revision = '08ca981ce365'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('requested_limit_paise', sa.BigInteger(), nullable=False),
    sa.Column('suggested_limit_paise', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommendation', sa.String(length=16), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('application', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=24), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_limit_paise', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_assessments_buyer', 'credit_assessments', ['company_id', 'buyer_id', 'computed_at'], unique=False)
    # ### end Alembic commands ###

    # RLS is applied here rather than left to `python -m app.db rls`. A tenant
    # table that exists without a policy is readable across tenants until
    # somebody remembers to run that command, and "somebody remembers" is not a
    # security control. FORCE matters: without it the owning role — which is the
    # role the application connects as — bypasses the policy entirely.
    op.execute("ALTER TABLE credit_assessments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE credit_assessments FORCE ROW LEVEL SECURITY")
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON credit_assessments")
    # NULLIF guards the empty string: an unset variable yields NULL, and
    # `company_id = NULL` is NULL rather than true, so no rows. Fail closed.
    op.execute(
        "CREATE POLICY tenant_isolation ON credit_assessments "
        "USING (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid) "
        "WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)"
    )

    # The application does not connect as the table's owner, so a new table is
    # unreachable until its roles are granted. The grants in app/db.py are
    # ON ALL TABLES at the time they run, which does not reach a table created
    # by a later migration — so this migration grants its own.
    for role in ("crp_app", "crp_worker"):
        op.execute(
            "DO $$ BEGIN "
            f"IF EXISTS (SELECT FROM pg_roles WHERE rolname = '{role}') THEN "
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON credit_assessments TO {role}; "
            "END IF; END $$"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_assessments_buyer', table_name='credit_assessments')
    op.drop_table('credit_assessments')
    # ### end Alembic commands ###
